apiVersion: v1
kind: Service
metadata:
  name: api-gateway-core-service
  labels:
    app: api-gateway-core-service
spec:
  selector:
    app: api-gateway-core
  ports:
    - port: 80
      targetPort: 8004
