apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-gateway-web
  name: api-gateway-web
spec:
  selector:
    matchLabels:
      app: api-gateway-web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway-web
    spec:
      containers:
      - image: idockerhub.jd.com/api-gateway/webserver:latest
        imagePullPolicy: Always
        name: api-gateway-web
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
