apiVersion: v1
kind: Service
metadata:
  name: api-gateway-web-service
  labels:
    app: api-gateway-web-service
spec:
  selector:
    app: api-gateway-web
  ports:
    - port: 80
      targetPort: 9004
