# 启动服务端口
server:
  port: 11005

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ucuc_java?useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: 53598528
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    time-zone: Asia/Shanghai

# 天权接入配置
dright:
  baseUrl: http://cityos-dev.jdcityos.com
  clientCredentials: client_credentials
  clientId: 5f97c6e1e4b08cf54ddfe6b3
  clientSecret: piZbqaeV7vUVbYqr63bOMmtk88lqVsxZ0GK9KI067h8VxlK5euUKh5JTnLSb5qoRwC0lnIASDwQDHdX4h558i5bbFVW4F8hZJiz1sPysLNwMwUOPlz1iixHM8VWoU2kHdWp8qqiOb5oHQObAwtP7HpfSPzQQFBztvR7IuvNaNHbbJwTvOvSinS4RZ13Hsg46heFPcI0qIfdyY74PBdFz3yiWRWAeqo2CUCYrHwqwTzdqtLUqpBtOFZshADwK3FDSD3k0kckW2VakxSjZHMjpQdWvIZpz4GgwwQZbyc
  clientUrl: /api/cityos/oauth/web/v1/oauth/token
  tokenVerify: /api/cityos/oauth/web/v1/oauth/sso/verify

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jdicity.lyd.dao
  type-aliases-super-type: java.lang.Object
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  production: false #swagger开启关闭，true关闭
  basic:
    enable: true #是否认证
    username: liyingda #认证用户名
    password: 123456 #认证密码

debug: true
