server:
  port: 8004

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000

cache:
  memory:
    enabled: true
  redis:
    enabled: false

gateway:
  sign:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjQPSB+yzJgOv1TIdOPODbHeknNuoR6kKaiCeeYlHuSk9w3ahUcdrCUvwDyRTszpVJxmeowI2KAieUezZpBr4C4kUkdKfwdnR02Vid0nhRbovn9B+OI8IiiqIUIplDVYf16Th2Vjim1R94BbfdeR8OOUlwFtruSNydXUF140O0MQIDAQAB
    privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKNA9IH7LMmA6/VMh0484Nsd6Sc26hHqQpqIJ55iUe5KT3DdqFRx2sJS/APJFOzOlUnGZ6jAjYoCJ5R7NmkGvgLiRSR0p/B2dHTZWJ3SeFFui+f0H44jwiKKohQimUNVh/XpOHZWOKbVH3gFt915Hw45SXAW2u5I3J1dQXXjQ7QxAgMBAAECgYBcArsMG0210ESs/1HvRZ6RwLzsziWErVyWjhCOUunMfPNjMHq0BWt/RJgnZgi2IwS/DOTVlpjvZKF8LSmQbi1eukbhSTn+zqDjlWFJ3F1V3JRXM9QQA8l1x4l4SfFNDlrS4t1o6txBHutmgcH4B+E4PE1KdK9a5+SHOlRhuK/2AQJBAM5NBOdfUWJERvjGtl2xyE25HbMJqQCQ/rQ22dNlOe85FU+Jze6lNRAIL0IkNPsociTZszIpG0q7w0HM8nlm11ECQQDKlSKCtJhITWlZDfEJbJulzwOqyoD4BGe7HfVYirLNfJAfek3/l9o8RJuyJIoWiNHBMB2TuW4WLMdm99DCh5bhAj8TVyUei9EVZVFCAV8XaZNdtf0Sy9UMOIuoWXwSVWsZAkD9M+4acWKIHjxP9xUAdso8qiwih7gHSZMEmDIjL4ECQQCKvRY0c6AzLCjw33ZrIOF77cmyJxuqP8IWyQ6lA+AukJdXp3hRilrgmZATsaiMhEk6yEwJRp4ZO7OYVjG3eAqhAkAsMpDumJSF2Hk3lKOFHeObuxZVDR86aeCTaqHGnciWuhZf89yQ0lge7L7s3dQVMDR2NLSNqpmOFr1eUeMVTua4
  encrypt:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjQPSB+yzJgOv1TIdOPODbHeknNuoR6kKaiCeeYlHuSk9w3ahUcdrCUvwDyRTszpVJxmeowI2KAieUezZpBr4C4kUkdKfwdnR02Vid0nhRbovn9B+OI8IiiqIUIplDVYf16Th2Vjim1R94BbfdeR8OOUlwFtruSNydXUF140O0MQIDAQAB
    privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAMSWBgB0fCCoulRqc8uPi1K4BKhblkvBdBrEERPTAj0dykR87qHW3nJnFYXrlQwS5Hvg4KmMjpoFrMglLFy3aOL/t2LDt/WREZx5ax5eTlhrqyovIoD7kaYVRsKHlOxK/MsCbNS9HMaShA77s5JXsZvop1o/adLJBZ9IhvvbYI9BAgMBAAECgYBkKpEaUEAjH/X5J1ijIxv5ZPwykKAvL34qWTbeZAji/Tff18x7uBEWN8I2v4ftY/75w+aVXaIXhsa4IIDPKUEObGEb0BChVQjdz/h9OMxaq8evSXvve12nixbX84S/NvsPY5it2vsxg+7OgBxAavXNOS/ILiti9VrB7trAtd/hFQJBAOHnO0GcC4HR0NvBtCoOIVl8egkNxxNb7soI4hoebu9VoQv1Xoh+lJFXrhiewUdQSEA/fJNWUS5eLZM8/LUL67MCQQDexuJjQ6NNadyFcRLr3IbkKqmrYWeRphq0Wd+kkgN/OO9y3ecaC9egOR/JIA0mkJCir8fLAVn+lBmWV7r2B087AkAH5aBxq7XPRPlrJTtaGQJbcXmGpX+nEpinYWYeCaBRJ4oos9wpI1uoNQt1+t7A0nKkJFQDhonx+ALZ2dDvt0n3AkBoxnNdKkeYtixAGnFCuwI6N5J7ByG1z8CJiCd1+DJq2HVNue3iQyWTtqorZsaol59e1HuMD8Oqxy7Nlc9ZvRBXAkBOt0lR4s5WQBDbb6S48i73ZMBf5CrazEE+tyGH6dL4dNcVB9x6EvDnC1LpKr6NhpkPprZ8YOyHEjrgY1Ly9fej

