Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('jzt-api', 'http://10.221.114.134:8025/jzt-api', null, '/api/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-api', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('zhanyi-enterprise-img', 'http://10.241.171.216:8077/zhanyi-enterprise', null, '/enterprise/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('zhanyi-enterprise', 'http://10.241.171.216:8077/zhanyi-enterprise', null, '/enterprise/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('joycity', 'http://10.240.161.149:8080/joycity', null, '/joycity/joycity/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('joycity-upload', 'http://10.240.161.149:8080/joycity', null, '/joycityupload/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('joycity-coupon', 'http://10.240.16.191:8080/joycity-coupon', null, '/joycity-coupon/joycity-coupon/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('joycity-coupon', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('wangfujing-upload', 'http://10.240.5.84:8072/wangfujing-weapp-server', null, '/joycity-coupon/joycity-coupon/(?<segment>.*)', ' /$\{segment}', '1');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('wangfujing-upload2', 'http://10.240.5.84:8072/wangfujing-weapp-server', null, '/joycity-coupon/joycity-coupon/(?<segment>.*)', ' /$\{segment}', '1');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('wangfujing', 'http://10.240.5.84:8072/wangfujing-weapp-server', null, '/wangfujing/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujing', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('jzt-app-upload', 'http://172.25.117.154:8020/jzt-app', null, '/app/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('jzt-app', 'http://172.25.117.154:8020/jzt-app', null, '/app/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-app', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('zhanyi-enterprise-admin-upload', 'http://172.25.77.235:8078/zhanyi-enterprise-admin', null, '/enterprise-admin/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('zhanyi-enterprise-admin', 'http://172.25.77.235:8078/zhanyi-enterprise-admin', null, '/enterprise-admin/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('zhanyi-enterprise-admin', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('uia', 'http://10.221.174.122:6001/uia', null, '/uum/uum/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('uia', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('suqian-proxy', 'http://172.25.107.26:6001/suqian-proxy', null, '/suqianproxy/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('suqian-proxy', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('icity-gateway', 'http://172.23.208.130:8080/icity-gateway', null, '/icitygateway/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('wangfujingadmin', 'http://172.25.87.191:8067/wangfujing-admin-server', null, '/wangfujingadmin/wangfujingadmin/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('wangfujingadmin', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('jzt-temporary-server', 'http://172.24.85.238:8011/jzt-temporary-server', null, '/jzt-temporary-server/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('jzt-temporary-server', 'RequestBodyGetData');
Insert into cfg_nacos(gateway_id, uri, predicate, regular_path, actual_path, parts_key) values ('icity-gateway-pre', 'http://172.24.124.81:8080/icity-gateway-pre', null, '/icity-gateway-pre/(?<segment>.*)', ' /$\{segment}', null);
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'HeaderCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'RequestBodyParse');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'AppSignCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'AccessTokenCheck');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'RequestBodyDecrypt');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'ContentTypeChange');
Insert into cfg_filter(gateway_id, value) VALUES ('icity-gateway-pre', 'RequestBodyGetData');
